apiVersion: apps/v1
kind: Deployment
metadata: 
  name: auth-svc
  labels: 
    app: auth-svc
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: auth-svc
  template:
    metadata:
      labels:
        app: auth-svc
    spec:
      containers: 
      - name: auth-svc
        image: muhamedjasim/auth-svc:latest
        ports:
        - containerPort: 50051
        env:
          - name: PORT
            value: ":50051"
          - name: DB_URL
            value: "postgres://cityvibe:jasi123@postgres-service:5432/auth_svc"
          - name: JWT_SECRET_KEY
            value: "r343nfse84"

---

apiVersion: v1
kind: Service
metadata: 
  name: auth-svc-service
spec:
  selector:
    app: auth-svc
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
